# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-28 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0003_auto_20161011_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runone',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
