# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-28 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0004_auto_20161028_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runone',
            name='slug',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
