# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-29 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0005_auto_20161028_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runone',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
